# Generated by Django 4.0.5 on 2022-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
